"""Materialize a pruned, runnable WPT checkout holding only the emitting tests.

WHAT "RUNNABLE" REQUIRES
A WPT test is not a standalone file.  It needs the wpt CLI and tools/ (to
serve and run), the harness in resources/, the shared helpers in common/, the
IDL files idlharness fetches from interfaces/, and whatever support files sit
next to it -- handlers (*.py), sub-resources, reference pages, helper scripts.
Missing any of those does not raise an error; the test runs and quietly makes
fewer requests than it does in the full tree.

THE RULE
  1. Infrastructure, always: the root files, tools/, resources/, common/,
     interfaces/, fonts/, images/, media/, .well-known/.
  2. Every top-level directory that holds a selected test, or that a selected
     test was SEEN fetching from in the access log: all of its non-test files
     (support, references, handlers), plus the selected tests themselves.
     Tests in it that did not emit are left out.
  3. A fresh MANIFEST.json, generated by `wpt manifest` inside the new tree,
     so `wpt run` sees exactly the selected tests and nothing else.

Rule 2 is deliberately generous with support files and strict with tests: a
support file too many costs disk, a support file too few silently changes
what a test does.  The access-log paths make it cover cross-directory loads
(a fetch/ test pulling /html/resources/...), which a per-directory rule alone
would miss.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys

from . import manifest as man_mod
from .console import Console

INFRA_DIRS = ("tools", "resources", "common", "interfaces", "fonts", "images",
              "media", ".well-known")
SKIP_NAMES = {".git", "_venv3", "_venv", ".wptcache", "__pycache__",
              "MANIFEST.json", "lna-retarget", ".tox", "node_modules"}


def _test_sources(man: dict) -> set:
    """Every source path the manifest lists as a test of any non-support type."""
    out: set = set()

    def walk(node, path):
        if isinstance(node, dict):
            for k, v in node.items():
                walk(v, f"{path}/{k}" if path else k)
        elif isinstance(node, list):
            out.add(path)

    for kind, tree in man.get("items", {}).items():
        if kind != "support":
            walk(tree, "")
    return out


def _logged_top_dirs(rows: list) -> set:
    dirs = set()
    for r in rows:
        for entry in r.get("logged", []):
            # "GET :8000/html/resources/x.js"
            path = entry.split(" ", 1)[-1]
            path = path[path.find("/"):] if "/" in path else ""
            top = path.strip("/").split("/", 1)[0]
            if top:
                dirs.add(top)
    return dirs


def build(wpt: str, census_json: str, out: str, console: Console,
          force: bool = False, manifest: bool = True) -> dict:
    with open(census_json, encoding="utf-8") as fh:
        census = json.load(fh)
    rows = census["rows"]
    emitted_urls = {r["url"] for r in rows if r["emitted"]}
    if not emitted_urls:
        raise SystemExit(f"{census_json} has no emitting tests -- nothing to build")

    man = man_mod.load(wpt)
    url_to_src = man_mod.source_files(man, emitted_urls)
    keep_sources = set(url_to_src.values())
    all_tests = _test_sources(man)

    top_dirs = {s.split("/", 1)[0] for s in keep_sources}
    top_dirs |= {d for d in _logged_top_dirs(rows)
                 if os.path.isdir(os.path.join(wpt, d))}
    top_dirs |= {d for d in INFRA_DIRS if os.path.isdir(os.path.join(wpt, d))}

    if os.path.exists(out):
        if not force:
            raise SystemExit(f"{out} exists; pass --force to replace it")
        shutil.rmtree(out)
    os.makedirs(out)

    console.header(f"subtree: {len(emitted_urls)} emitting test URL(s) from "
                   f"{len(keep_sources)} source file(s)")
    # 1. root files (wpt launcher, config, lint rules, ...)
    for name in sorted(os.listdir(wpt)):
        src = os.path.join(wpt, name)
        if os.path.isfile(src) and name not in SKIP_NAMES:
            shutil.copy2(src, os.path.join(out, name))

    # 2. infra + selected directories
    copied_tests = copied_support = 0
    for top in sorted(top_dirs):
        infra = top in INFRA_DIRS
        for root, dirs, files in os.walk(os.path.join(wpt, top)):
            dirs[:] = [d for d in dirs if d not in SKIP_NAMES]
            rel_root = os.path.relpath(root, wpt).replace(os.sep, "/")
            for f in files:
                rel = f"{rel_root}/{f}"
                is_test = rel in all_tests
                if is_test and not infra and rel not in keep_sources:
                    continue                     # a test that did not emit
                dst = os.path.join(out, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(os.path.join(root, f), dst)
                if is_test and not infra:
                    copied_tests += 1
                else:
                    copied_support += 1
        console.info(f"{top + '/':<32} copied")

    # the list the tree was built from travels with it
    with open(os.path.join(out, "NETWORK-TESTS.txt"), "w", encoding="utf-8",
              newline="\n") as fh:
        fh.writelines(u + "\n" for u in sorted(emitted_urls))

    stats = {"test_urls": len(emitted_urls), "test_sources": copied_tests,
             "support_files": copied_support, "dirs": sorted(top_dirs)}
    console.info(f"{copied_tests} test source(s), {copied_support} support/infra file(s)")

    # 3. a manifest for exactly this tree
    if manifest:
        console.info("generating MANIFEST.json  (./wpt manifest)")
        r = subprocess.run([sys.executable, "./wpt", "manifest", "--no-download"],
                           cwd=out, capture_output=True, text=True)
        if r.returncode != 0:
            console.error("wpt manifest failed:\n" + (r.stderr or r.stdout)[-2000:])
            stats["manifest"] = False
        else:
            stats["manifest"] = True
            console.info(f"MANIFEST.json written to {out}")
    return stats
