"""Render the census as TREE.md: where the emitting tests live, and how the
MANIFEST.json that indexes them is shaped."""
from __future__ import annotations

import collections
import json
import os

MANIFEST_SHAPE = """\
```text
MANIFEST.json
├── version            manifest format version (wpt tooling checks it)
├── url_base           "/"
└── items
    ├── testharness    ← JS tests that report pass/fail (the bulk)
    │   └── fetch                      directory  →  nested object
    │       └── api
    │           └── basic
    │               └── request-head.any.js         source file  →  list
    │                   [ "<sha1 of source>",
    │                     ["fetch/api/basic/request-head.any.html",        {…}],
    │                     ["fetch/api/basic/request-head.any.worker.html", {…}] ]
    │                         ↑ one entry per URL the source expands into;
    │                           {…} = extras: timeout, script_metadata
    │                           (META: script= deps, global=, variants)
    ├── reftest        ← [url, [[reference_url, "=="|"!="]], {…}]
    ├── print-reftest
    ├── crashtest
    ├── manual         ← needs a human; not run by the census
    └── support        ← helpers, handlers, resources (never run)
```

Read it with plain `json`: walk `items[type]` as a tree of dicts until you
reach a list; element 0 is the source hash, each further element is
`[url, extras]` (`url` is `null` when it equals the source path).
`netcensus/manifest.py` does exactly this, and reads `script_metadata` to
tell a declared helper script apart from a request the test makes.
"""


def _tier(r: dict) -> int:
    """0 = none / cdp-only / error, 1 = runtime, 2 = static only."""
    if r.get("runtime"):
        return 1
    return 2 if r["emitted"] else 0


def render(census_json: str, subtree_manifest: str | None = None,
           depth: int = 2, top_n: int = 0) -> str:
    with open(census_json, encoding="utf-8") as fh:
        census = json.load(fh)
    rows = census["rows"]

    # [run, runtime, static-only] per bucket
    by_top: dict = collections.defaultdict(lambda: [0, 0, 0])
    by_sub: dict = collections.defaultdict(lambda: [0, 0, 0])
    by_type: dict = collections.defaultdict(lambda: [0, 0, 0])
    for r in rows:
        parts = r["url"].strip("/").split("/")
        top = parts[0]
        sub = "/".join(parts[:depth]) if len(parts) > depth else top
        t = _tier(r)
        for bucket, key in ((by_top, top), (by_sub, sub), (by_type, r["type"])):
            bucket[key][0] += 1
            if t:
                bucket[key][t] += 1

    n = census["n_tests"]

    def pct(k: str) -> str:
        return f"{census[k]} ({100.0 * census[k] / max(1, n):.1f}%)"

    out = [
        "# Test tree & manifest tree",
        "",
        f"Generated by `python -m netcensus tree` from "
        f"`{os.path.basename(census_json)}` ({census['generated']}): stock "
        f"headless Chrome, `--jobs {census['jobs']}`, "
        f"`--timeout {census['timeout']}`, `--settle {census['settle']}`.",
        "",
        "| | tests |",
        "|---|---:|",
        f"| run | {n} |",
        f"| **✔ emit at runtime** (`data/census.txt`) | **{pct('n_runtime')}** |",
        f"| ◦ static subresources only (`data/census-static.txt`) | {pct('n_static_only')} |",
        f"| · no network | {pct('n_none')} |",
        f"| ⚠ attempted, never reached the server | {census['n_cdp_only']} |",
        f"| ✖ errors | {census['n_errors']} |",
        f"| unattributed access-log lines (run-level) | {census['orphan_requests']} |",
        "",
        "## By test type",
        "",
        "| type | run | runtime | static only |",
        "|---|---:|---:|---:|",
    ]
    for k, (a, b, c) in sorted(by_type.items(), key=lambda kv: -kv[1][1]):
        out.append(f"| {k} | {a} | {b} | {c} |")

    out += [
        "",
        "## Test tree",
        "",
        "Directories that contain runtime emitters, sorted by count. Columns: "
        "**runtime** · static-only · run. A second level (top 8) is shown for "
        "directories with 25 or more runtime emitters.",
        "",
        "```text",
    ]
    tops = sorted(((k, v) for k, v in by_top.items() if v[1]),
                  key=lambda kv: (-kv[1][1], kv[0]))
    if top_n:
        tops = tops[:top_n]
    w = max([len(k) for k, _ in tops] + [24]) + 4
    out.append(f"    {'':<{w}}{'runtime':>8}{'static':>8}{'run':>8}")
    for i, (top, (a, b, c)) in enumerate(tops):
        last = i == len(tops) - 1
        out.append(f"{'└──' if last else '├──'} {top + '/':<{w}}{b:>8}{c:>8}{a:>8}")
        if b < 25:
            continue
        subs = sorted(((k, v) for k, v in by_sub.items()
                       if k.startswith(top + "/") and v[1]),
                      key=lambda kv: (-kv[1][1], kv[0]))[:8]
        for j, (sk, (sa, sb, sc)) in enumerate(subs):
            bar = "    " if last else "│   "
            elbow = "└──" if j == len(subs) - 1 else "├──"
            name = sk.split("/", 1)[1] + "/"
            out.append(f"{bar}{elbow} {name:<{w - 4}}{sb:>8}{sc:>8}{sa:>8}")
    out += ["```", ""]

    zero = sorted(k for k, v in by_top.items() if not v[1])
    if zero:
        out += [f"<details><summary>{len(zero)} directories with no runtime "
                f"emitter</summary>", "",
                ", ".join(f"`{z}`" for z in zero), "", "</details>", ""]

    out += ["## Manifest tree", "", MANIFEST_SHAPE]
    if subtree_manifest and os.path.exists(subtree_manifest):
        with open(subtree_manifest, encoding="utf-8") as fh:
            m = json.load(fh)
        out += ["The pruned tree's own `wpt-network/MANIFEST.json` "
                "(source files per type):", "",
                "| type | source files |", "|---|---:|"]
        for kind, tree in sorted(m.get("items", {}).items()):
            out.append(f"| {kind} | {_count_leaves(tree)} |")
        out.append("")
    return "\n".join(out) + "\n"


def _count_leaves(node) -> int:
    if isinstance(node, dict):
        return sum(_count_leaves(v) for v in node.values())
    return 1 if isinstance(node, list) else 0
